version: '3'

services:
  db_admin: 
    hostname: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    env_file: default.env
    depends_on:
      - db
  db: 
    hostname: db
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    env_file: default.env
    environment: 
      - "PGDATA=/storage/pg"
    volumes:
      - "./db:/storage/pg"